language: rust
rust: stable

os: linux

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

jobs:
  allow_failures:
    env:
      - CAN_FAIL=true
  fast_finish: true
  include:
    - name: check
      script:
        - cargo check --manifest-path ffimage/Cargo.toml --no-default-features
        - cargo check --manifest-path ffimage/Cargo.toml --features rayon
        - cargo check --manifest-path ffimage-yuv/Cargo.toml --no-default-features
        - cargo check --manifest-path ffimage-yuv/Cargo.toml --features rayon
    - name: test
      script:
        - cargo test --manifest-path ffimage/Cargo.toml --no-default-features
        - cargo test --manifest-path ffimage/Cargo.toml --features rayon
        - cargo test --manifest-path ffimage-yuv/Cargo.toml --no-default-features
        - cargo test --manifest-path ffimage-yuv/Cargo.toml --features rayon
    - name: fmt
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
    - name: clippy
      env: CAN_FAIL=true
      before_script:
        - rustup component add clippy
      script:
        - cargo clippy -- -D warnings
