language: rust
rust: stable

os: linux
cache: cargo

jobs:
  allow_failures:
    env:
      - CAN_FAIL=true
  fast_finish: true
  include:
    - name: check
      script:
        - cargo check --no-default-features
        - cargo check --features rayon
    - name: test
      script:
        - cargo test --no-default-features
        - cargo test --features rayon
    - name: fmt
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
    - name: clippy
      env: CAN_FAIL=true
      before_script:
        - rustup component add clippy
      script:
        - cargo clippy -- -D warnings
